modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
authors = "${mod_authors}"
credits = "Assets and Idea by toomanykitkats"
displayName = "${mod_name}"
description = '''${mod_description}'''
displayTest = "MATCH_VERSION"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"